module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: [
    "collapse",
    "collapsing",
    "show",
    "dropdown-menu",
    "dropdown-item",
    "table",
    "table-dark",
    "table-hover",
    "table-responsive",
    "af-tooltip",
    "af-popover",
    "font-weight-bold",
    "font-weight-medium",
    "font-weight-lighter",
    "navbar",
    "navbar-light",
    "navbar-expand-sm",
    "fixed-top",
    "nav-item",
    "nav-link",
    "navbar-toggler",
    "navbar-brand",
    "navbar-collapse",
    "navbar-nav",
    "icon-bar",
    "top-bar",
    "middle-bar",
    "bottom-bar",
  ],
};
